version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    container_name: bambu_web_1
    links:
      - "db:database"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=bambu
    container_name: bambu_db_1


    